* Cl-ownpress 

#+begin_quote
Convert inputs to outputs.
#+end_quote

To elaborate a bit further:

1. Collect inputs from anywhere. e.g tweets, local org files, Reddit/HN comments
2. Process the inputs to produce outputs e.g convert them to HTML files

That's it folks. clownpress is a general framework that shall allow you to do
just that, and only that.

It is not an "I don't know what I am doing" end-user software, it is meant to
maximize hackability. Code is the UI.

* Architecture

1. <<Provider>>

   Providers are instances of =provider= class. Job of a provider is to:

   #+begin_quote
   collect [[input][inputs]] and their [[dependency][dependencies]] directly into the database
   #+end_quote

   A provider when invoked can do whatever is necessary to build a dependency
   graph for everything that should be published.

2. <<Builder>>

   A Builder is an instance of =builder= class. Job of a builder is to:

   #+begin_quote
   convert an input to a publishable asset
   #+end_quote

Clownpress itself is an orchestrator, which provides a framework for building a
dependency tree of inputs provided by providers, and then resolves the
dependency tree into publishable assets built by builders. 

** Glossary
- <<input>> : A file which should be built to produce a publishable asset
- <<dependency>> : A file which must be built before an [[input]]
- [[Provider]]
- [[Builder]]
